// Package taglines provides fun one-liners for pdfify CLI output.
// Displayed in --version, --help header, and progress UI.
package taglines

import (
	"math/rand"
)

// All contains every tagline. Generate a random one with Random().
var All = []string{
	"Making PDFs beautiful since 2026",
	"Your markdown deserves better than a browser print dialog",
	"LaTeX power, markdown simplicity",
	"Because copy-paste into Word is not a workflow",
	"Turning plaintext into presentation-ready documents",
	"Docker-powered document alchemy",
	"From markdown to masterpiece",
	"PDFs that don't look like they were made in 1997",
	"Where mermaid diagrams go to become vectors",
	"Professional documents for people who hate Word",
	"One command, zero compromises",
	"The PDF pipeline your markdown deserves",
	"Because pandoc alone was too easy",
	"Callouts, mermaids, and tables — oh my!",
	"XeLaTeX in a container so you don't have to install it",
	"Making documentation look like it had a graphic designer",
	"From README to boardroom-ready",
	"The last mile between markdown and print",
	"Frontmatter-driven perfection",
	"Your CI/CD pipeline's favorite PDF tool",
	"Like a typewriter, but with Docker",
	"Markdown goes in, beauty comes out",
	"No fonts were harmed in the making of this PDF",
	"Containerized typesetting for the modern age",
	"Because life's too short for ugly documents",
	"Where code blocks get syntax highlighting",
	"The tool that makes your docs team jealous",
	"Turning git repos into printable knowledge",
	"PDFs with personality",
	"Your markdown, but make it fashion",
	"Obsidian callouts? We got you",
	"Watch mode: for the indecisive writer",
	"Themes: because one look isn't enough",
	"From frontmatter to final draft",
	"The PDF factory that fits in your terminal",
	"Making pandoc feel fancy",
	"Where every heading gets the respect it deserves",
	"Table of contents included, existential dread not included",
	"Watermarks for when you mean DRAFT",
	"Page breaks in all the right places",
	"Section numbers that actually make sense",
	"Your docs, but with better margins",
	"LaTeX preambles so you don't have to write them",
	"The missing link between markdown and management",
	"Pixel-perfect PDFs from plaintext prose",
	"One binary to PDF them all",
	"Mermaid diagrams that actually render",
	"Cross-platform via the magic of containers",
	"Paper sizes from A4 to Legal and beyond",
	"Typography nerds approve this tool",
	"PDF generation at the speed of Docker pull",
	"For when HTML export just won't cut it",
	"Turning your thoughts into trees... of contents",
	"Embedded in Go, powered by pandoc, styled with love",
	"Reproducible documents, every single time",
	"--preview: for the chronically curious",
	"The tool that reads your frontmatter and your mind",
	"A PDF for every occasion, a theme for every mood",
	"Where markdown meets its final form",
	"Professional output, unprofessional taglines",
	"Configured in YAML, delivered in PDF",
	"Tables that don't overflow the page (usually)",
	"Code blocks that wrap gracefully (always)",
	"No LaTeX knowledge required — we did the suffering for you",
	"Powered by open source and mild frustration with Word",
	"Your preferences file called — it says you're welcome",
	"CLI first, questions later",
	"Because you deserve better than wkhtmltopdf",
	"Bringing order to the chaos of documentation",
	"The PDF tool that respects your time",
	"Smart enough to auto-detect your heading structure",
	"Now with 100% more progress bars",
	"Update yourself — we support that too",
	"Where every callout type gets its own color",
	"The doctor is in: --doctor checks everything",
	"Export your knowledge, not your patience",
	"Roboto: the font that makes everything look better",
	"Helvetica is overrated — fight us",
	"From scratch to PDF in under a minute",
	"The little Go binary that could",
	"Container-native document generation",
	"Headings so pretty they could be art",
	"Numbered sections that count on you",
	"Page footers that know which page they're on",
	"Signatures not included — that's your job",
	"pdfify: it's like make, but for PDFs",
	"A love letter to structured documents",
	"Where YAML frontmatter meets LaTeX backend",
	"The fastest path from idea to print",
	"Works on my machine (and yours, thanks to Docker)",
	"Themes: giving your PDFs a personality since v1.0",
	"Party theme: for when your quarterly report needs pizzazz",
	"Default theme: for when you want to keep your job",
	"Every setting: CLI, frontmatter, or preferences — your choice",
	"Markdown in, PDF out, problems gone",
	"Your terminal's favorite typesetter",
	"Building documents the way software should be built",
	"Debug your docs, not your PDF tool",
	"Clean output, clean conscience",
	"Making the simple things simple and the complex things possible",
	"Where good defaults meet full customization",
	"The antidote to documentation dread",
}

// Random returns a random tagline.
func Random() string {
	return All[rand.Intn(len(All))]
}
